### ISSUE TITLE
django生成数据库时报错：ModuleNotFoundError: No module named 'crud'

### ISSUE THREAD

**Issue by long3ck** [RogersLei/django-vue#2]
Failed to get real commands on module "django-vue": python process died with code 1: Traceback (most recent call last):
  File "D:\PyCharm 2017.3.3\helpers\pycharm\_jb_manage_tasks_provider.py", line 25, in <module>
    django.setup()
  File "E:\virtualenv\ENVs\example_env\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "E:\virtualenv\ENVs\example_env\lib\site-packages\django\apps\registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "E:\virtualenv\ENVs\example_env\lib\site-packages\django\apps\config.py", line 116, in create
    mod = import_module(mod_path)
  File "E:\virtualenv\ENVs\example_env\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'crud'

**Comment by Snowty** [comment]
同问

**Comment by RogersLei** [comment]
抱歉，，问题解决了么。。隔了这么久才看到

**Comment by Snowty** [comment]
已经解决啦，谢谢~

NXLrogers <notifications@github.com> 于2020年2月13日周四 下午6:36写道：
